### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by rmja** [dahomey-technologies/Dahomey.Cbor#103]
Hi,

Could any of the maintainers of this repo put out some details about the path going forward?
I really like the library and use it in several of my projects, but I have to use my own fork to fix some quirks.
There are outstanding issues and PR's that could use a comment from the maintainers.

Again, thank you for a really good and beautifully designed library.

Rasmus

**Comment by mcatanzariti** [comment]
Hi @rmja,

I have been busy on other projects the last months but I can take some time to check last issues and PRs 

Thank you for the good words,

M.
