### ISSUE TITLE
[feature request] Allow fields and properties of Type ISomeInterface

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#11]
could you please allow serializing properties and fields whose type is an Interface? like this:

```
public class Tree
{
        public IDictionary<string, string> TreeMetaData { get; }
}
```

**Comment by mcatanzariti** [comment]
Yes it would be possible for collection interfaces like IDictionary<>, ICollection<>, IList<>, IEnumerable<> and ISet<>.

For custom interfaces it would be possible if an implementation it provided through a factory (ObjectMapping.MapCreator).

Any other idea?

**Comment by TMaddox** [comment]
sounds great, how about custom abstract classes?

**Comment by mcatanzariti** [comment]
same thing than custom interface

**Comment by mcatanzariti** [comment]
Automatic instantiation of List<> for ICollection<>, HashSet<> for ISet<>, Dictionary<> for IDictionary<>

For a custom interface:
```csharp
            CborOptions options = new CborOptions();
            options.Registry.ObjectMappingRegistry.Register<IFoo>(objectMapping =>
                objectMapping
                    .AutoMap()
                    .MapCreator(o => new Foo())
            );
```

For a custom abstract class:
```csharp
            CborOptions options = new CborOptions();
            options.Registry.ObjectMappingRegistry.Register<AbstractBar>(objectMapping =>
                objectMapping
                    .AutoMap()
                    .MapCreator(o => new Bar())
            );
```
