### ISSUE TITLE
Feature Suggestion: Support for reading multiple CBOR objects sequentially from a stream.

### ISSUE THREAD

**Issue by seithman** [dahomey-technologies/Dahomey.Cbor#115]
Ran across this project while trying to write a C# implementation for the AT Protocol. Ran into a problem that the AT Protocol uses WebSocket messages with two CBOR objects (not an array) written to the payload sequentially. The current Dahomey.Cbor library doesn't seem to support reading two objects out of a single stream.

I've begun working on an update to support this. It's in the extremely early stages (nowhere near ready to share other than providing a link to my fork and telling you the code is in the multi branch of my fork). Wondering i:
* There are future plans to add support to this to the library.
* If there would be enough interest in having this feature for me to put in the extra effort to make it worthy of a pull request to the project.

**Comment by mcatanzariti** [comment]
Hi @seithman,

There is no plan to add this feature but please, propose a pull request.

Cheers,

Michaël

PS: the PR should include auto tests

**Comment by seithman** [comment]
Oh yes, the PR will absolutely include tests. it's mostly what I have left to work on (plus adding asynchronous methods).

Granted, part of the process is my need to learn a few of the intricacies of testing in XUnit. I'm mostly and embedded software guy when it comes to my professional work, so these forays into other areas of development are always an adventure. ;)

Thanks!

**Comment by mcatanzariti** [comment]
fix in https://github.com/dahomey-technologies/Dahomey.Cbor/commit/49dbdf2dc12942773e3d24f0291bb854e41b0364
