### ISSUE TITLE
[bug] readonly properties cannot be deserialized via a custom constructor

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#12]
```
public class Tree
    {
        [CborProperty("id")]
        public const string Id = "Tree.class";

        [CborProperty("foo")]
        public string Foo { get; }

        [CborProperty("name")]
        public readonly string name;
        
        [CborProperty("whatever")]
        public static int whatever;

        public Tree() { }
        ....
    }
```
There seems to be a bug with the implementation of readonly, const and static fields/properties. I am using the attribute as you told me to in https://github.com/dahomey-technologies/Dahomey.Cbor/issues/7

The exception is "Operation is not valid due to the current state of the object."

**Comment by mcatanzariti** [comment]
Hi,

I cannot reproduce the problem with your example.
Could you post the exact code you wrote for serializing the object and the full callstack of the exception, please?

**Comment by TMaddox** [comment]
I have done some more testing and found out the following:
1. readonly fields and get only properties (aka. read only properties) are always deserialized to null:
```
public class Tree
{
    [CborProperty("name")]
    public string Name { get; }

    public Tree() { }
}
```
this example serializes correctly, but Name = null after deserialization

2. If a class contains no empty constructor (`public Tree() { }`) AND a readonly field/property, static or const field, it will throw `System.InvalidOperationException: "Operation is not valid due to the current state of the object."`, the [CborConstructor] attribute does not work in this scenario (at least I couldn't figure something out)

**Comment by mcatanzariti** [comment]
A readonly property/field in a class with a default constructor will never be initialized during a deserialization because the library has no mean to set a readonly property/field.

After the fix, a readonly property/field initialized by a custom constructor decorated by CborConstructorAttribute (or configured in Cbor by API) will be deserialized
