### ISSUE TITLE
ReadDataItem return type

### ISSUE THREAD

**Issue by Odonno** [dahomey-technologies/Dahomey.Cbor#126]
Hello,

It's me again.

I am working on performance improvement and more specifically memory allocation. I have usage of `ReadDataItem` on multiple occasions. I have the need for `ReadOnlySpan<byte>` (so that it stays in the stack) but I also sometimes need to pass it to another object instance. This is not possible with a `Span`. Best option is to use a `ReadOnlyMemory<byte>`. I made the change locally and it works like a charm using the inner `Span` of the `ReadOnlyMemory<byte>`.

What do you think about this change?

* How to implement multiple return types on a single method? (as it is not possible in C#)
* I may have missed some articles but there may be a better option than `ReadOnlyMemory<byte>`?

**Comment by mcatanzariti** [comment]
Hi @Odonno,

First I'm curious to know why you need to call CborReader.ReadDataItem directly as the library is meant to be use through CborConverters. Unless you create yourself a converter for a specific requirements.

Then, the implementation of ReadDataItem gives directly a span of the internal buffer associated to CborReader. If you need a ReadOnlyMemory<byte> or even a byte array, you just need to copy the span returned by ReadDataItem to whatever instantiated memory buffer you need.

Cheers,

Michaël

**Comment by Odonno** [comment]
> First I'm curious to know why you need to call CborReader.ReadDataItem directly as the library is meant to be use through CborConverters. Unless you create yourself a converter for a specific requirements.

I need to lazy deserialize value per my API design. So, I need to store the `byte[]` part in an object as long as it is needed by the user of the API. Hence, the need for a `ReadOnlyMemory<byte>`. I found that the best solution to my problem.

> Then, the implementation of ReadDataItem gives directly a span of the internal buffer associated to CborReader. If you need a ReadOnlyMemory or even a byte array, you just need to copy the span returned by ReadDataItem to whatever instantiated memory buffer you need.

Finding that I can use the inner span of a `ReadOnlyMemory<byte>` but I cannot do the other way (put a Span in a `ReadOnlyMemory<byte>`). I mean, I can but I would have to allocate a temporary `byte[]` which will consume unnecessary memory. I will make a PR for this change.
