### ISSUE TITLE
[bug] bug with readonly fields

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#13]
this works:
```
    public class Tree
    {
        [CborProperty("age")]
        public int Age { get; }

        [CborConstructor]
        public Tree(int age)
        {
            Age = age;
        }
    }
```
while this fails on serialization (didn't test deserialization):
```
    public class Tree
    {
        [CborProperty("age")]
        private readonly int _age;

        [CborConstructor]
        public Tree(int age)
        {
            _age = age;
        }
    }
```
Exception is:
`System.Reflection.TargetInvocationException: "Exception has been thrown by the target of an invocation."` and `CborException: Cannot find a field or property named age on type TestApp.Tree`

**Comment by mcatanzariti** [comment]
I have reproduced the issue.
It is caused by mismatch between the field name and the constructor parameter name (_name vs name).
I'm thinking about a solution

**Comment by mcatanzariti** [comment]
Solution:

 public class Tree
    {
        [CborProperty("age")]
        private readonly int _age;

        [CborConstructor("age")]
        public Tree(int age)
        {
            _age = age;
        }
    }
