### ISSUE TITLE
[bug] ignoring does not work correctly

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#15]
This works:
```
    public class Tree
    {
        [CborProperty("age")]
        public readonly int _age;

        [CborConstructor]
        public Tree(int age)
        {
            _age = age;
        }
    }
```
While this throws: `CborException: Cannot find a field or property named age on type TestApp.Tree`
```
    public class Tree
    {
        [CborProperty("age")]
        public readonly int _age;

        [CborIgnore]
        public long Age2 => 5;     // 1

        [CborConstructor]
        public Tree(int age)
        {
            _age = age;
        }
    }
```
if you replace the long in the row // 1 with an int, it does work. I tried to ignore it with the [CborIgnore] approach and this one https://github.com/dahomey-technologies/Dahomey.Cbor/issues/10, but both doesn't help

**Comment by mcatanzariti** [comment]
Please, could you give the whole sample with the CborOptions you initialized?

**Comment by TMaddox** [comment]
Really hard to say in a few words, can't really break it down to my usual  tree example. Basically, I am adding a few custom types with: `CborOptions.Default.Registry.ConverterRegistry.RegisterConverter(typeof(byte[]), new DsonObjectConverter<byte[]>(x => x, y => y));` (note: dson = cbor)

and then I am adding exactly what you suggested right here https://github.com/dahomey-technologies/Dahomey.Cbor/issues/10

In case you want to have a closer look about how I added these options: https://github.com/helium-party/radixdlt-net/blob/feature/serialization/HeliumParty.RadixDLT/src/HeliumParty.RadixDLT.Dson/Mapping/DsonOutputMapping.cs

**Comment by mcatanzariti** [comment]
The issue was about the framwork not being able to match constructor parameter name with field _name because of the '_'.

The type int or long of the field Age is not changing the problem
