### ISSUE TITLE
[Question] ObjectMappingRegistry with private fields/properties

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#16]
I am adding a custom object mapping registry as advised here https://github.com/dahomey-technologies/Dahomey.Cbor/issues/6 like this:

```
CborOptions.Default.Registry.ObjectMappingRegistry.Register<Tree>(om =>
            {
                om.AutoMap();
                om.ClearMemberMappings();
                om.MapMember(o => o.MyField);
                om.MapMember(o => o.MyField2);
            });
```
how can I do this with private fields/properties? I do not wan't to add the ObjectMapping in the class itself (athrought I have not tested this, if it would even work).

Like this:
```
public class Tree
{
    private int _age;
    private string _name;
    ....
}
```
and:
```
CborOptions.Default.Registry.ObjectMappingRegistry.Register<ECSignature>(om =>
            {
                om.AutoMap();
                om.ClearMemberMappings();
                om.MapMember(o => o.name); // this does obviously not work
            });
```
Is there a possibility to add "fields to serialize" via the [CborProperty("**name**")] and have a List<string> _toSerialize or something like that?

**Comment by mcatanzariti** [comment]
I provided 2 solutions in :
https://github.com/dahomey-technologies/Dahomey.Cbor/blob/master/src/Dahomey.Cbor.Tests/Issues/Issue0016.cs
