### ISSUE TITLE
[question] how to allow calling the base constructor on deserialization?

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#19]
Take the following example:
```
    public class Tree : Plant
    {
        [CborProperty("age")]
        public int Age { get; }

        [CborConstructor]
        public Tree(int age, string name) : base(name)
        {
            Age = age;
        }
    }

    public abstract class Plant
    {
        [CborProperty("name")]
        public int Name { get; }

        public Tree(string name)
        {
            Name = name;
        }
    }
```
Name will not be serialized and on deserialization always be null (obviously), how can I allow serializing and invoking the base constructor too? I can't set the [CborConstructor] attribute in abstract classes

And thanks again for all the quick fixes and explanations, really appreciate it!

**Comment by mcatanzariti** [comment]
In the following sample:

https://github.com/dahomey-technologies/Dahomey.Cbor/blob/master/src/Dahomey.Cbor.Tests/Issues/Issue0019.cs

Name is serialized and deserialized without any problem.

Feel free to reopen the issue if I did not identify the right problem

**Comment by TMaddox** [comment]
My mistake, I had a private field in my abstract class instead of a protected one. Thanks!
