### ISSUE TITLE
Is there something like a converters class available?

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#2]
Take the following example:
```
class Tree{
    public Fruit _apple;
    ...
}

class Fruit{
    ...
}
```

**Task:** 
I want to serialize the class Tree

**How I think I can achieve it right now:**
 - write a custom converter for class Fruit (class MyFruitConverter : CborConverterBase<Fruit>)
 - write a custom serializer for class Tree and in the Method (override void Write(...)) use the custom serializer for fruit

**How I would like to do it:**
 - write a custom serializer for class Fruit and do this:
```
var converters = new CborConverters();
converters.Add(new MyFruitConverter(...));
await Cbor.SerializeAsync(myTree, myStream, converters);
```

**Why do I want to do it this way?**
I have got something like MyTree.MyBranch.MyFruit.MyFruitColor.andSoOn

Could you please tell me if this is either possible at the moment, a planned feature or not planned at all.

Is there a documentation for this library available? (couldn't find one)

**Comment by mcatanzariti** [comment]
Hi TMaddox,

You can achieve what you want to do in 2 ways.

1. You can decorate you class with the CborConverterAttribute:

```csharp
[CborConverter(typeof(MyFruitConverter))]
class Fruit
{
}
```

2. You can manually register you converter:

```csharp
CborConverter.Register(typeof(Fruit), new MyFruitConverter ());
```
By the way you don't need to write any custom serializer for the class Tree. The framework should find and use your registered custom converter when serializing the field Tree._apple.

Sorry for the lack of documentation. I wrote this library on my spare time and did not yet find time to write a complete documentation.

Let me know if you have any other problem.

Michaël

**Comment by TMaddox** [comment]
Works perfectly, thanks!
