### ISSUE TITLE
Question : How to use CborWriter

### ISSUE THREAD

**Issue by jonassix** [dahomey-technologies/Dahomey.Cbor#23]
Hi,

How can i use the cborwriter to apply a member mapping at runtime.
Aka the ObjectMapping stored in CborOptions?

This is for usage with a custom CborConverterBase<T>

**Comment by mcatanzariti** [comment]
Hi Jonassix,

I'm not sure to understand your question.
Please, could you provide an example of what you need : the class and the expected result 

Thank you

**Comment by jonassix** [comment]
Let's imagine we have the following class.

```csharp
  class TestClass
        {
            [SerializationOutput(OutputMode.Hash | OutputMode.Persist | OutputMode.All)]
            public string VisibleField { get; set; }
            [SerializationOutput(OutputMode.None)]
            public string HiddenField { get; set; }
        }
```

Somewhere in my code i want to hash (Sha256) TestClass but to create a correct hash, only certain fields may be used(serialized). 
So in this example. The class obj on serialisation may only contain VisibleField. (aka Outputmode.Hash)
My idea was to do something like this.

```csharp
options.Registry.ConverterRegistry.RegisterConverter(typeof(TestClass),
                new DsonObjectConverter<TestClass>(OutputMode.Persist)
```

And i know i can do something like this 

```csharp
 CborOptions.Default.Registry.ObjectMappingRegistry.Register<TestClass>(om =>
            {
                om.AutoMap();
                om.ClearMemberMappings();
                om.MapMember(o => o.VisibleField);

            });
```

I just need to find a way to combine the two. Thank you for any advice you can give me!

**Comment by mcatanzariti** [comment]
ObjectMapping is meant to be used with built-in ObjectConverter<T>

https://github.com/dahomey-technologies/Dahomey.Cbor/blob/master/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs

This converter is dedicated to custom classes and is based on reflection of fields and properties of the class.
ObjectMapping and MemberMapping exist to let ObjectConverter<T> be aware of the mapping between the custom class and a Cbor buffer.

It means that ObjectMapping is tightly coupled to ObjectConverter<T> and has no meaning outside of this coupling.

Moreover, ObjectConverter<T> is rather complex and is not meant to be overridden.
 
The way to customize the behavior of ObjectConverter<T> is the exact role of ObjectMapping/MemberMapping.

Based on this statements, I don't understand what you're trying to achieve with DsonObjectConverter

**Comment by mcatanzariti** [comment]
I just checked your code here:

https://raw.githubusercontent.com/helium-party/radixdlt-net/master/HeliumParty.RadixDLT/src/HeliumParty.RadixDLT.Dson/DsonManager.cs

It seems you define a different mapping between your classes and the Cbor library through the class DsonConverter and then you serialize only ByteStrings into the Cbor buffer.

It works but it kind of hacks the way Dahomey.Cbor is meant to be used

May be you should not use DsonConverter with a class you want to map but instead use it with each member of the class you want to map


```csharp
CborOptions.Default.Registry.ObjectMappingRegistry.Register<TestClass>(om =>
            {
                om.AutoMap();
                om.ClearMemberMappings();
                om.MapMember(o => o.VisibleField).SetMemberConverter(new DsonObjectConverter<string>());

            });

**Comment by mcatanzariti** [comment]
You should also be aware that ObjectConverter is serializing a cbor map which keys are the class properties/fields serialized as cbor names and values are the properties/fields values serialized from the CborConverters associated with their types.

If it's not what you want to achieve, please provide a sample class and the exact cbor result you want (it could be a matching json or a link to cbor me)

**Comment by jonassix** [comment]
> May be you should not use DsonConverter with a class you want to map but instead use it with each member of the class you want to map

Yeah, kinda realised that. I am rebuilding the serialisation, but i lack some knowledge of dahomey.cbor lib.

I want to build a custom objectconverter that also serialises a cbor map but kan skip certain properties when they have a certain attribute. 
That objectconverter should be a generic converter that accepts any object. 

Imagine i need to use Cbor to communicate with a Http endpoint.
But when sending data to store new record i may not send the field Id.

```csharp
        class Person
        {
            //do not serialize Id field on insert/creation of object
            public string Id { get; set; }
            public string SomeField { get; set; }
        }

        class PersonInsert
        {
            public string SomeField { get; set; }
        }

        class PersonDelete
        {
            public string Id { get; set; }
        }
```

Imagine that i have a class model with 1000 different types
I know i can create multiple classes , and use automapper to map between them. But this is just a dummy example to explain my goal.
And in this example i would have 1000 types and 2000 Dto(data transfer objects). 

If i can write a custom objectconverter that utilizes a cbor map and reflection, i could technicaly avoid all this hassle.

**Comment by jonassix** [comment]
So after some investigation i believe i need to use the IObjectMappingConvention
I've done a dummy test and seems to work.

```csharp
    public class DsonObjectMappingConvention : IObjectMappingConvention
    {
        private readonly IObjectMappingConvention defaultObjectMappingConvention = new DefaultObjectMappingConvention();
        private readonly INamingConvention DsonNamingConvention = new DsonNamingConvention();

        public void Apply<T>(SerializationRegistry registry, ObjectMapping<T> objectMapping) where T : class
        {
            defaultObjectMappingConvention.Apply<T>(registry, objectMapping);
            

            //replace this with reflection method
            //if (typeof(T) == typeof(IntObject))
            //{
            //    objectMapping.ClearMemberMappings();
            //    objectMapping.MapMember(o => (o as IntObject).IntValue);
            //}



            objectMapping.SetNamingConvention(DsonNamingConvention);
        }
    }
```

**Comment by jonassix** [comment]
I've implemented it this way https://github.com/helium-party/radixdlt-net/blob/feature/serialization-libinvestigation/HeliumParty.RadixDLT/src/HeliumParty.RadixDLT.Core/Serialization/Dson/DsonMappingConvention.cs

And this is my unit test. 

```csharp. 
class TestClass
        {
            [SerializationOutput(OutputMode.All)]
            public int IntValue { get; set; }
            [SerializationOutput(OutputMode.Hash)]
            public int IntSecondValue { get; set; }
            [SerializationOutput(OutputMode.Hidden)]
            public string HiddenValue { get; set; }
            public string DummyValue { get; set; }
            public byte[] DummyBin { get; set; }
        }

        [Fact]
        public void Dson_MappingConventions_Test()
        {
            //arrange
            var o = new TestClass() {
                IntValue = 300 , IntSecondValue = 20, HiddenValue="secret", DummyValue="known",
                DummyBin = Bytes.FromHexString("0123456789abcdef")
        };

            //act
            var dson = _manager.ToDson(o);            
            var o2 = _manager.FromDson<TestClass>(dson, OutputMode.All);

            //assert
            o2.IntValue.ShouldBe(o.IntValue);
            o2.IntSecondValue.ShouldBe(o.IntSecondValue);
            o2.HiddenValue.ShouldBeNull();
            o2.DummyValue.ShouldBe(o.DummyValue);
            o2.DummyBin.ShouldBe(Bytes.FromHexString("0123456789abcdef"));
        }
```
Everything seems to work. So if you don't see any issues with this implementation i believe you may close this issue/question.

Thank you for all your help!

**Comment by mcatanzariti** [comment]
seems good to me!
