### ISSUE TITLE
Failure to deserialize a foreign cbor file. 

### ISSUE THREAD

**Issue by jonassix** [dahomey-technologies/Dahomey.Cbor#24]
Hi, 

When deserializing this file to a Cbor Object we expect to find 8 keys. (not the zip, but the file in the zip)
[messageParticle3.zip](https://github.com/dahomey-technologies/Dahomey.Cbor/files/3584584/messageParticle3.zip)

However with dahomey , we only receive 4 keys.

```csharp
            //arrange
            var data = ResourceParser.GetResource("messageParticle3.dson");


            //act
            //dahomey lib
            CborObject d = null;
            using (var ms = new System.IO.MemoryStream())
            {
                ms.Write(data, 0, data.Length); // TODO modify this once .net standard 2.1 is used
                d= await Cbor.DeserializeAsync<CborObject>(ms, CborOptions.Default);
            }

            //peter/cbor lib
            var cbor = CBORObject.DecodeFromBytes(
                            data, CBOREncodeOptions.Default);

            //assert
            d.ShouldNotBeNull();
            cbor.ShouldNotBeNull();
```

See both output screenshot (one with dahomey, one with a other lib(peter/cbor))
used by dahomey
![image](https://user-images.githubusercontent.com/22755764/64440348-15d99e80-d0cc-11e9-92c8-2fb9ad3b3b5d.png)

Used by a different lib.
![image](https://user-images.githubusercontent.com/22755764/64440200-d9a63e00-d0cb-11e9-8eb1-675ed4eb3f6a.png)

Are we doing something wrong with the dahomey lib or?

Thank you for taking a look at this. 

_Note : the file messageParticle3.dson is not generated by us, and we do not have control over it's contents. However we need to be able to deserialize it's full contents_

**Comment by mcatanzariti** [comment]
fixed

By the way, if you want to deserialize from a byte array, you don't need to instantiate a MemoryStream. A ReadOnlySpan<byte> can be automatically created in the stack by calling Cbor.Deserialize:

```csharp
byte[] data = ResourceParser.GetResource("messageParticle3.dson");
CborObject obj = Cbor.Deserialize<CborObject>(data);
```
