### ISSUE TITLE
Feature request : Protected empty constructors

### ISSUE THREAD

**Issue by jonassix** [dahomey-technologies/Dahomey.Cbor#25]
Hi,

I understand that dahomey needs a constructor (mapped or otherwise) and as such i've always added a empty contructor(if there is a non empty constructor present) so serializing would be possible. 

However i would prefer if that empty constructor could be "protected" instead of public. 
This helps forcing our users to use the wanted constructor. 

Is something like this possible?

**Comment by mcatanzariti** [comment]
Implemented in v[1,4,3](https://github.com/dahomey-technologies/Dahomey.Cbor/releases/tag/1.4.3)
