### ISSUE TITLE
Attribute [CborIgnore] ignores everything beneath it

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#3]
Take the following example:
```
public class Tree
    {
        [CborProperty("name")]
        public string Name { get; set; }

        [CborProperty("age")]
        [CborIgnore]
        public int Age { get; set; }

        [CborProperty("type")]
        public TreeType Type { get; set; }

        public Tree() { }
    }
```
**How it should work:**
Serializes class Tree with Name and Type.

**How it works right now:**
Serializes class Tree with Name.

From a few quick tests I learned that all properties below the first [CborIgnore] are ignored

**Comment by mcatanzariti** [comment]
Fixed (https://github.com/dahomey-technologies/Dahomey.Cbor/commit/77fbe4f1c72f47cf2abf67ed182a14b0bdef332d)
