### ISSUE TITLE
Bug: Stability and NRE with empty lists

### ISSUE THREAD

**Issue by jtorvald** [dahomey-technologies/Dahomey.Cbor#31]
I like the interface of this library. More intuitive and comparable to the Newtonsoft.JSON library than PeterO Cbor library. It just feels that this library needs some more love to get mature?

The code below crashes with a NRE on the Keys that are null.

            public class TestData
            {
                        public int Id { get; set; }

                        [CborIgnore]
                        public DateTime Date { get; set; }
                        public List<string> Keys { get; set; }
            }

            // gives null reference exception
            var data = new TestData() { Id = 1, Date = DateTime.Now };
            var stream2 = new MemoryStream();
            await Cbor.SerializeAsync(data, stream2, CborOptions.Default);
            var result = await Cbor.DeserializeAsync<TestData>(stream2, CborOptions.Default);

**Comment by jtorvald** [comment]
I submitted a pull request to solve this issue #32

**Comment by mcatanzariti** [comment]
Yes the library is young. The first drop of code as been committed on June 29th.

Thank you for your patience and your collaboration.

It's appreciated!

**Comment by jtorvald** [comment]
@mcatanzariti No, thank you for dedicating your time to write this library.

**Comment by jonassix** [comment]
Indeed, it's an awesome creation!
