### ISSUE TITLE
Bug: non ASCII strings are not supported

### ISSUE THREAD

**Issue by jtorvald** [dahomey-technologies/Dahomey.Cbor#34]
I get this exception but I've no idea how to interpret this and where to look what might fail. Please explain what is expected and at what level.

Unhandled Exception: Dahomey.Cbor.CborException: [123] Expected major type TextString (3)
   at Dahomey.Cbor.Serialization.CborReader.Expect(CborMajorType majorType) in src/Dahomey.Cbor/Serialization/CborReader.cs:line 698

**Comment by mcatanzariti** [comment]
Basically or means that you are trying to deserialize a string c# type but the read cbor type is not a text string.

If you give me the full callstack, I will be able to give you more details

**Comment by jtorvald** [comment]
> Unhandled Exception: Dahomey.Cbor.CborException: [231] Expected major type TextString (3)
>    at Dahomey.Cbor.Serialization.CborReader.Expect(CborMajorType majorType) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 698
>    at Dahomey.Cbor.Serialization.CborReader.ReadRawString() in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 262
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadMapItem(CborReader& reader, MapReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 238
>    at Dahomey.Cbor.Serialization.CborReader.ReadMap[TC](ICborMapReader`1 mapReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 337
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 133
>    at Dahomey.Cbor.Serialization.Converters.MemberConverter`2.Read(CborReader& reader, Object obj) in/src/Dahomey.Cbor/Serialization/Converters/MemberConverter.cs:line 51
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadValue(CborReader& reader, Object obj, ReadOnlySpan`1 memberName) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 174
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadMapItem(CborReader& reader, MapReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 299
>    at Dahomey.Cbor.Serialization.CborReader.ReadMap[TC](ICborMapReader`1 mapReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 337
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 133
>    at Dahomey.Cbor.Serialization.Converters.AbstractCollectionConverter`2.ReadArrayItem(CborReader& reader, ReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/AbstractCollectionConverter.cs:line 73
>    at Dahomey.Cbor.Serialization.CborReader.ReadArray[TC](ICborArrayReader`1 arrayReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 355
>    at Dahomey.Cbor.Serialization.Converters.AbstractCollectionConverter`2.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/AbstractCollectionConverter.cs:line 40
>    at Dahomey.Cbor.Serialization.Converters.MemberConverter`2.Read(CborReader& reader, Object obj) in/src/Dahomey.Cbor/Serialization/Converters/MemberConverter.cs:line 51
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadValue(CborReader& reader, Object obj, ReadOnlySpan`1 memberName) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 174
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadMapItem(CborReader& reader, MapReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 299
>    at Dahomey.Cbor.Serialization.CborReader.ReadMap[TC](ICborMapReader`1 mapReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 337
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 133
>    at Dahomey.Cbor.Serialization.Converters.AbstractCollectionConverter`2.ReadArrayItem(CborReader& reader, ReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/AbstractCollectionConverter.cs:line 73
>    at Dahomey.Cbor.Serialization.CborReader.ReadArray[TC](ICborArrayReader`1 arrayReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 355
>    at Dahomey.Cbor.Serialization.Converters.AbstractCollectionConverter`2.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/AbstractCollectionConverter.cs:line 40
>    at Dahomey.Cbor.Serialization.Converters.MemberConverter`2.Read(CborReader& reader, Object obj) in/src/Dahomey.Cbor/Serialization/Converters/MemberConverter.cs:line 51
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadValue(CborReader& reader, Object obj, ReadOnlySpan`1 memberName) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 174
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.ReadMapItem(CborReader& reader, MapReaderContext& context) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 272
>    at Dahomey.Cbor.Serialization.CborReader.ReadMap[TC](ICborMapReader`1 mapReader, TC& context) in/src/Dahomey.Cbor/Serialization/CborReader.cs:line 337
>    at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.Read(CborReader& reader) in/src/Dahomey.Cbor/Serialization/Converters/ObjectConverter.cs:line 133
>    at Dahomey.Cbor.Cbor.Deserialize[T](ReadOnlySpan`1 buffer, CborOptions options) in/src/Dahomey.Cbor/Cbor.cs:line 62
>    at Dahomey.Cbor.Cbor.DeserializeAsync[T](Stream stream, CborOptions options) in/src/Dahomey.Cbor/Cbor.cs:line 24
>    at CLI.Program.Test() in /Program.cs:line 117
>    at CLI.Program.Main(String[] args) in /Program.cs:line 21
>

**Comment by jtorvald** [comment]
Didn't manage to figure it out yet. The library encodes it fine but on the decode it gives this error. I will write a test for it and either fix the bug or commit the test.

**Comment by jtorvald** [comment]
Added a test in pull request #37

**Comment by mcatanzariti** [comment]
It seems the Cbor buffer you added to Issue0034.cs is not valid and thus does match the provided json string.

You can verify here the invalidity of the provided Cbor buffer:
http://cbor.me/?bytes=A266726573756C7481A362696400646B657973F66C7061727469636970616E747383A262696418476475736572A9624964636A3166684C656E677468434D006647656E64657200644E616D65664AC3B87267656E6443697479F6675461674C696E65F666417661746172F6634167650069497343686172697479F4A262696418486475736572A9624964636E3268684C656E677468434D006647656E64657200644E616D65664A65726F6D796443697479F6675461674C696E65F666417661746172F6634167650069497343686172697479F4A262696418496475736572A96249646371336B684C656E677468434D006647656E64657200644E616D65664D61676769656443697479F6675461674C696E65F666417661746172F6634167650069497343686172697479F46673746174757318C8

And this is the Cbor buffer matching the provided json string:
http://cbor.me/?bytes=A1(66(726573756C74)-81(A1(6C(7061727469636970616E7473)-83(A2(62(6964)-18.47-64(75736572)-A2(62(6964)-63(6A3166)-64(6E616D65)-67(4AC3B87267656E)))-A2(62(6964)-18.48-64(75736572)-A2(62(6964)-63(6E3268)-64(6E616D65)-66(4A65726F6D79)))-A2(62(6964)-18.49-64(75736572)-A2(62(6964)-63(71336B)-64(6E616D65)-66(4D6167676965)))))))
