### ISSUE TITLE
[feature request] add support for System.Collections.Immutable

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#4]
At the moment it seems like System.Collections.Immutable (https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable) is not supported, are you planning on adding this?

**Comment by mcatanzariti** [comment]
Fixed (https://github.com/dahomey-technologies/Dahomey.Cbor/commit/87c4da783e8acaec1447e56cbc463aac145f3a9e)
