### ISSUE TITLE
[feature request] Possibility to serialize private fields

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#5]
Is there a possibility to serialize private fields/properties?

If not, I would like to request this feature. How about serializing/deserializing the field/property if the [CborProperty] attribute is used, no matter the access modifier. It wouldn't make any sense to decorate a field with a [CborProperty] which shouldn't be serialized anyways.

**Comment by mcatanzariti** [comment]
implemented https://github.com/dahomey-technologies/Dahomey.Cbor/releases/tag/1.1.0

**Comment by mcatanzariti** [comment]
If you decorate a private/protected field/property with [CborProperty], it will be serialized/deserialized.
