### ISSUE TITLE
[Question] Issue with serializing ImmutableList<>

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#53]
Dahomey Version: 1.10.3

An exception gets thrown when executing the following UnitTest:
```
        [Fact]
        public void HashUniverseConfigWithoutError()
        {
            var universeConfig = new RadixUniverseConfig(
                name: "sdf",
                description: "asdf",
                systemPublicKey: new ECKeyManager().GetRandomKeyPair().PublicKey,
                timestamp: System.DateTime.UtcNow.Ticks,
                type: RadixUniverseType.Development,
                port: 1,
                magic: 1,
                genesis: new List<Atom>()
                );

            universeConfig.GetHash();
        }
```
please check the class RadixUniverseConfig right here (don't want to put this huge textwall here): https://github.com/helium-party/radixdlt-net/blob/feature%2Fnetwork/HeliumParty.RadixDLT/src/HeliumParty.RadixDLT.Network/Universe/RadixUniverseConfig.cs

The Method GetHash() serializes the RadixUniverseConfig and hashes the cbor byte array.
Unfortunately, the following exception gets thrown:
![grafik](https://user-images.githubusercontent.com/20703314/72086925-067f9180-3308-11ea-813c-fdeb443bb8b7.png)
The 1/2 inner exception: `TargetInvocationException: Exception has been thrown by the target of an invocation.`

As the exception clearly states that the property named genesis is causing the problems, I tried to narrow down the issue further.

If List<Atom> is used instead of ImmutableList<Atom> the Unit test passes. Meaning there has to be an Issue with ImmutableList<>.

I tried to abstract this issue to make it simpler for you, but unfortunately, this one passes which leaves me with no clue:
```
        [CborDiscriminator("dahomey.immutabletest", Policy = CborDiscriminatorPolicy.Always)]
        public class ImmutableTest
        {
            [SerializationOutput(OutputMode.All)]
            public ImmutableList<Atom> MyList { get; set; }

            public ImmutableTest(List<Atom> list)
            {
                MyList = list?.ToImmutableList();
            }
        }

        [Fact]
        public void Should_Serialize_And_Deserialize()
        {
            var manager = new DsonManager();

            var obj = new ImmutableTest(new List<Atom>{new Atom()});

            var serialized = manager.ToDson(obj, OutputMode.Hash);
            var deserialized = manager.FromDson<ImmutableTest>(serialized, OutputMode.Hash);
        }
```

**Comment by mcatanzariti** [comment]
The problem is the type mismatch between genesis as a property and genesis as constructor argument. The framework does not know how to process the conversion

**Comment by mcatanzariti** [comment]
The conversion is far to be obvious. Indeed in your constructor you call: ToImmutableList()

**Comment by mcatanzariti** [comment]
The best option currently, is to write a custom converter for this config class

**Comment by mcatanzariti** [comment]
Another option could be to offer the possibility to give more options in the CborConstructorAttribute

**Comment by TMaddox** [comment]
Thanks for the insight, I have a better understanding of the issue now.

Before you go through the hurdle of implementing this, I might have found a simple solution on my side.

I just did an override of my ctor and now I got those two, unit test passes:

```
        public RadixUniverseConfig(
            string name,
            string description,
            ECPublicKey systemPublicKey,
            long timestamp,
            RadixUniverseType type,
            int port,
            int magic,
            **ImmutableList<Atom> genesis**)
        {
            Name = name;
            Description = description;
            SystemPublicKey = systemPublicKey;
            Timestamp = timestamp;
            Type = type;
            Port = port;
            Magic = magic;
            **Genesis = genesis;**
        }

        public RadixUniverseConfig(
            string name,
            string description,
            ECPublicKey systemPublicKey,
            long timestamp,
            RadixUniverseType type,
            int port,
            int magic,
            **List<Atom> genesis**)
        {
            Name = name;
            Description = description;
            SystemPublicKey = systemPublicKey;
            Timestamp = timestamp;
            Type = type;
            Port = port;
            Magic = magic;
            **Genesis = genesis?.ToImmutableList();**
        }
```

So basically I can use the ctor, just as I wanted and created another one for serialization.
Do you see any problem with this solution?

**Comment by TMaddox** [comment]
So to summarize I think the best and cleanest way is to always have a ctor which exactly has the signature of all fields/properties and override it if required?

**Comment by mcatanzariti** [comment]
I think your solution is perfect!
Thank you :)
