### ISSUE TITLE
Corrupted JSON string returning from Cbor.ToJson()

### ISSUE THREAD

**Issue by berkayalpcakal** [dahomey-technologies/Dahomey.Cbor#56]
Hello,

Thanks for the great repo. I am trying to add CBOR decoding support to [ROS#](https://github.com/siemens/ros-sharp), where the CBOR encoded ROS messages are to be deserialized in Unity3D.

I am trying to deserialize the json string returned by Cbor.ToJson() method. I used both the [Newtonsoft ](https://www.newtonsoft.com/json) and the [.NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-overview) API but I get similar exceptions complaining about the corrupted json string.

### Observed
* Receive cbor encoded byte array from rosbridge_suite (a dummy PointCloud2 message)
* Call function Cbor.ToJson()
```csharp
ReadOnlySpan<byte> span = new ReadOnlySpan<byte>(byteArray);
string json = Cbor.ToJson(span);
```
* Try deserializing via Newtonsoft or .NET API. Here is an example of the returned json string and the exception observed;

> **{"Invalid JavaScript property identifier character: '. Path 'msg.header.stamp', line 1, position 104."}**

```
"{\"topic\":\"/custom_pc2\",\"msg\":{\"width\":32,\"is_dense\":true,\"point_step\":0,\"height\":16,\"header\":{\"stamp\":{h'73656373':1585771534,h'6E73656373':462513923},\"frame_id\":\"debug\",\"seq\":3400},\"data\":h'',\"fields\":[],\"row_step\":0,\"is_bigendian\":false},\"op\":\"publish\"}"
```
### Expected
* Receive regularly encoded byte array from rosbridge_suite ( a dummy PointCloud2 message)
* No need for CBOR decoding, here is the returned json string from the ASCII decoding of the byte array;

```
"{\"topic\": \"/custom_pc2\", \"msg\": {\"width\": 32, \"is_dense\": true, \"point_step\": 0, \"height\": 16, \"header\": {\"stamp\": {\"secs\": 1585773050, \"nsecs\": 469499111}, \"frame_id\": \"debug\", \"seq\": 4659}, \"data\": \"\", \"fields\": [], \"row_step\": 0, \"is_bigendian\": false}, \"op\": \"publish\"}"
```

* This is the expected json string since it can be deserialized using Newtonsoft or .NET API without any exceptions.
* The differences between the two different json strings is at the **stamp** field.

Why could be the reason for that? 
Do you think that this could be a problem due to unsuccessful cbor encoding from rosbridge_suite side?

Kind regards.

**Comment by mcatanzariti** [comment]
@berkayalpcakal Cbor.ToJson() is just provided for debugging and is not compliant with JSON specification. It's meant to be use with http://cbor.me/ debugging web page.

If you want to deserialize a CBOR buffer from a ReadOnlySpan<byte> with Dahomey.Cbor, please use the following method in `Cbor` class
```csharp
 public static T Deserialize<T>(ReadOnlySpan<byte> buffer,  CborOptions? options = null);
```

It will mush faster than trying to transform the CBOR buffer to Json and the deserializing from Json with Newtonsoft.

Hope it helps.
