### ISSUE TITLE
[feature request] add possiblility to filter/modify object structure on serializing and deserializing

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#6]
I have to serialize the same object in different ways, with JSON (Newtonsoft.Json library) this is possible with a custom contract, which can be added to the serializer (Reference: https://www.newtonsoft.com/json/help/html/CustomContractResolver.htm)

Do you plan on adding something like this?

**Comment by mcatanzariti** [comment]
Hi TMaddox,

Could you please provide detailed examples of the different ways you would like to serialize the same object?

Newtonsoft json contracts have many options and I'm not sure which one you would like to see implemented

**Comment by TMaddox** [comment]
Sorry for the unclear OP, I'll try to find a small and accurate example

Basically I want to choose at runtime, wether a property or field should be serialized or not.

Consider the following classes:
```
public class Tree
    {
        public string Name { get; set; }
        public int Age { get; set; }

        public Tree() { }
        ....
    }

public class MyContract : CborBaseContract
    {
        protected override IList<CborProperty> CreateProperties(Type type)
        {
            IList<CborProperty> properties = base.CreateProperties(type);

            if (typeof(Tree) == type)
            {
                properties.Where(p => p.PropertyName == "Name").ToList();
            }

            return properties;
        }
    }
```
Now I want to do this:
```
public void MyMethod()
    {
        CborContract myCustomCborContract = new MyContract();
        Cbor.Contract = myCustomCborContract;
        var serialized = Cbor.Serialize(new Tree("myTree", 10))      // I know this won't work, just a concept to keep it simple
        // serialized should contain the property "Name", but not "Age"
    }
```

**Comment by mcatanzariti** [comment]
implemented in https://github.com/dahomey-technologies/Dahomey.Cbor/releases/tag/1.1.0

**Comment by mcatanzariti** [comment]
Syntax with your example:

```csharp
public class Tree
{
    public string Name { get; set; }
    public int Age { get; set; }

    public Tree() { }
    ....
}

public void MyMethod()
{
    CborOptions options = new CborOptions();
    options.Registry.ObjectMappingRegistry.Register<Tree>(objectMapping =>
        objectMapping
            .AutoMap()
            .ClearMemberMappings()
            .MapMember(o => o.Name)
    );

    var serialized = Cbor.Serialize(new Tree("myTree", 10), options);
}
```

**Comment by TMaddox** [comment]
Thank you very much for implementing all my featue requests! I really appriciate it!

**Comment by mcatanzariti** [comment]
You're welcome!
Please let me know if all is working as expected.
