### ISSUE TITLE
[API] CborOptions and CborReader/CborWriter

### ISSUE THREAD

**Issue by tibel** [dahomey-technologies/Dahomey.Cbor#65]
Scope
- `CborReader` and `CborWriter` are not using `CborOptions`
- `CborOptions` is used by converters only

This brings me to the question:
Why `CborReader` and `CborWriter` have an `Options` property and take `CborOptions` as a constructor parameter when it is not used?

Suggestion
- change converter constructors to use `CborOptions` instead of `SerializationRegistry`
- remove `Options` property from `CborReader` and `CborWriter`

I know this would be a breaking change. Just wanted to write it down so it can be considered for next major release.

**Comment by mcatanzariti** [comment]
You are right!
I can change ObjectConverter constructor, it would not be a major breaking for this class is meant to be used internally.
I'm also going to add a new constructors to CborReader/CborWriter without the CborOption parameter, remove the Options property and mark the existing constructors as obsolete

**Comment by mcatanzariti** [comment]
fix in https://github.com/dahomey-technologies/Dahomey.Cbor/commit/d018f1b3165efa6f2ea49b6c878ff102f0a14686

**Comment by tibel** [comment]
Did not expect this to happen right now :star_struck:

Thanks  a lot @mcatanzariti
