### ISSUE TITLE
System.Formats.Cbor

### ISSUE THREAD

**Issue by tibel** [dahomey-technologies/Dahomey.Cbor#73]
With .NET 5 there is a new player in the field of CBOR. At least for the low-level API (CborReader and CborWriter).
- https://www.nuget.org/packages/System.Formats.Cbor/
- https://docs.microsoft.com/en-us/dotnet/api/system.formats.cbor
- https://github.com/dotnet/runtime/tree/master/src/libraries/System.Formats.Cbor/src/System/Formats/Cbor
- https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/libraries/System.Formats.Cbor

What are the future plans:
- keep low-level API?
- build converters on top of System.Formats.Cbor?

Also a comparison would be nice.

**Comment by tibel** [comment]
System.Formats.Cbor
- `CborWriter` cannot operate on top of `IBufferWriter<byte>`
- `CborReader` and `CborWriter` are classes

**Comment by mcatanzariti** [comment]
Hi @tibel 

I am not planning to switch to System.Formats.Cbor because, as you mentionned, their reader & writer are classes and would trigger additional allocations
