### ISSUE TITLE
Omit property name when serializing.

### ISSUE THREAD

**Issue by bruceharrison1984** [dahomey-technologies/Dahomey.Cbor#77]
Is there an easy way to omit the property name when serializing? The default serialization works fine in my case, but the protocol I am using is implicit, and doesn't include property names in the serialized payload. Currently I am writing custom convertors for each object, but wasn't sure if there was an easier way.

**Comment by mcatanzariti** [comment]
@bruceharrison1984,

The aim of this library is to translate C# class/structs fields or properties into Cbor properties.

If you wan't to get rid of properties, you could write a Cbor converter provider to automatically generate a cbor converter for each class by reflection but you would loose the different features offered by the built-in object mapping
