### ISSUE TITLE
Remove the requirement of having a public ctor with empty signature

### ISSUE THREAD

**Issue by TMaddox** [dahomey-technologies/Dahomey.Cbor#8]
At the moment it is required to have a public constructor without any arguments like this
```
public class Tree
    {
        ... some fields ...

        public Tree() { }
        ....
    }
```
Can you remove this requirement? Either allow a private constructor or remove this requirement as a whole?

**Comment by mcatanzariti** [comment]
Would you expect a constructor with parameters to be called?
If yes, what would be the strategy to invoke it?

**Comment by TMaddox** [comment]
I am using JSON and CBOR serialization in my project. For JSON I am using https://github.com/JamesNK/Newtonsoft.Json

I can't tell you how they do it, but I can tell you that I am able to serialize and deserialize objects to and from JSON without having a single constructor

I have adjusted my code to work with your lib and it's working right now (added `public MyClass(){}` ), but in case this is a quick fix, I would be happy if you implement this.

**Comment by mcatanzariti** [comment]
Please could you provide an example of a class without a default constructor, you use with newtonsoft json?

**Comment by TMaddox** [comment]
This is my class, I can serialize and deserialize it 
```
public class Tree
{
        public string Name { get; set; }
        public int Age { get; set; }
        public TreeType Type { get; set; }
}
```

**Comment by mcatanzariti** [comment]
The title of this issue is: Remove the requirement of having a public ctor with empty signature.
Do you just expect a parameterless constructor to be supported?

If you want also a constructor with parameters to be supported, I need an example with such a constructor to understand exactly what you want.

I hope I'm clearer

**Comment by mcatanzariti** [comment]
For instance, I could support this kind of ctor by trying to match the constructor parameters types and names with serialized properties or fields.

``` csharp
public class Tree
{
        public string Name { get; set; }
        public int Age { get; set; }
        public TreeType Type { get; set; }

        public Tree(string name, int age, TreeType type)
        {
                Name = name;
                Age = age;
                Type = type;
        }
}
```
Do you need this kind of feature?
If yes, the performance of this kind of process would be much lower.

**Comment by TMaddox** [comment]
It would help in some cases, but not in every one as for example I will have something like this:

```
public class Tree
{
        public string Name { get; set; }
        public int Age { get; set; }
        public TreeType Type { get; set; }

        public Tree(string name, int age)
        {
                Name = name;
                Age = age;
        }
        ... // some logic 
}
```

I will try to explain more clear, at the moment I need to have a constructor, which looks exactly like this: `public Tree() { }`

So I can instantiate my class tree everywhere like this: `new Tree()`, which I don't want.

I am sorry I can't tell you how they do it, but Newtonsoft.Json manages to serialize and deserialize classes which haven't got a single constructor (not that this would make any sense for most classes, but it removes the reqirement of having a `public Tree() { }`)

This isn't a pressing issue, it would enable me to make my project a bit cleaner but, if you want we can close this issue. (so you can focus on my other feature requests, which are more important, thanks by the way for the quick fixes!)

**Comment by mcatanzariti** [comment]
implemented in https://github.com/dahomey-technologies/Dahomey.Cbor/releases/tag/1.1.0

**Comment by mcatanzariti** [comment]
Syntax with your example:

```csharp
public class Tree
{
    public string Name { get; set; }
    public int Age { get; set; }
    public TreeType Type { get; set; }

    public Tree(string name, int age)
    {
        Name = name;
        Age = age;
    }
}

public void MyMethod()
{
    CborOptions options = new CborOptions();
    options.Registry.ObjectMappingRegistry.Register<Tree>(objectMapping =>
        objectMapping
            .AutoMap()
            .MapCreator(tree => new Tree(tree.Name, tree.Age))
    );

    ReadOnlySpan<byte> buffer = ...;
    Tree tree = Cbor.Deserialize<Tree>(buffer, options);
}
```

Another option is to decorated the Tree ctor with [CborConstructor]:

```csharp
public class Tree
{
    public string Name { get; set; }
    public int Age { get; set; }
    public TreeType Type { get; set; }

    [CborConstructor]
    public Tree(string name, int age)
    {
        Name = name;
        Age = age;
    }
}

public void MyMethod()
{
    ReadOnlySpan<byte> buffer = ...;
    Tree tree = Cbor.Deserialize<Tree>(buffer);
}
```
