### ISSUE TITLE
Method not found !!0 Dahomey.Cbor.Cbor.Deserialize<!0>(System.ReadOnlySpan`1<byte>,Dahomey.Cbor.CborOptions)

### ISSUE THREAD

**Issue by jtorvald** [dahomey-technologies/Dahomey.Cbor#86]
Hi! I've a situation that worked well before but suddenly fails.
I deserialize bytes into an object with Cbor.Deserialize<Payload>(bts);

That worked good before but for some reason I now get:
Method not found: !!0 Dahomey.Cbor.Cbor.Deserialize<!0>(System.ReadOnlySpan`1<byte>,Dahomey.Cbor.CborOptions)

When I switch to DeserializeAsync with a memory stream it works fine. Not sure if it's something in my code that has changed. I can not find it. Do you have any suggestion to what can cause this?

**Comment by mcatanzariti** [comment]
The method is still there !

```chsarp
public static T Deserialize<T>(ReadOnlySpan<byte> buffer, CborOptions? options = null);
```

**Comment by jtorvald** [comment]
Maybe it is not linker safe? I don't know it's been a while. From what I read above I solved it with the DeserializeAsync.

**Comment by mcatanzariti** [comment]
I don't understand what you mean by "not linker safe".

May be, could you provide a full repro of the problem ?
